function MangoolsGuideSection() {
  const steps = [
    {
      number: "1",
      title: "Open KWFinder",
      description:
        "Login to Mangools and open the KWFinder tool for keyword research.",
      example: "Start with a broad keyword idea.",
    },
    {
      number: "2",
      title: "Enter A Seed Keyword",
      description:
        "Type a keyword related to your niche or topic.",
      example: "Example: running shoes",
    },
    {
      number: "3",
      title: "Review Keyword Suggestions",
      description:
        "Look through keyword ideas generated by Mangools.",
      example: "Example: best running shoes for beginners",
    },
    {
      number: "4",
      title: "Check Keyword Difficulty",
      description:
        "Focus on keywords with lower difficulty scores and realistic ranking opportunities.",
      example: "Avoid highly competitive keywords.",
    },
    {
      number: "5",
      title: "Choose & Create Content",
      description:
        "Pick the best keyword and create content that matches search intent.",
      example: "Publish a detailed guide around the keyword.",
    },
  ];

  return (
    <section className="bg-slate-50 py-28 lg:py-36">

      <div className="max-w-7xl mx-auto px-6">

        {/* Heading */}
        <div className="max-w-5xl mx-auto text-center">

          <span className="inline-block px-5 py-2 rounded-full bg-emerald-100 text-emerald-700 text-sm font-semibold tracking-wide">
            Mangools Walkthrough
          </span>

          <h2 className="mt-8 text-5xl md:text-6xl lg:text-7xl font-extrabold text-slate-900 leading-[1.08]">
            How To Use Mangools For Keyword Research
          </h2>

          <p className="mt-10 text-xl md:text-2xl leading-9 text-slate-600 max-w-3xl mx-auto">
            Follow this simple process to find keyword opportunities,
            evaluate difficulty, and choose topics that have a better
            chance of ranking in Google.
          </p>

        </div>

        {/* Cards */}
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8 mt-20">

          {steps.map((step) => (
            <div
              key={step.number}
              className="p-10 rounded-3xl border border-slate-200 bg-white shadow-lg hover:shadow-2xl hover:-translate-y-2 transition-all duration-300"
            >

              <div className="w-16 h-16 rounded-full bg-emerald-100 text-emerald-700 flex items-center justify-center text-2xl font-bold mb-6">
                {step.number}
              </div>

              <h3 className="text-3xl font-bold text-slate-900 mb-5">
                {step.title}
              </h3>

              <p className="text-lg leading-8 text-slate-600 mb-8">
                {step.description}
              </p>

              <div className="bg-slate-50 border border-slate-100 p-6 rounded-2xl">

                <p className="text-base font-medium text-slate-700">
                  {step.example}
                </p>

              </div>

            </div>
          ))}

        </div>

      </div>

    </section>
  );
}

export default MangoolsGuideSection;